server:
  port: 8080
spring:
  application:
    name: "onlinefilms"
  datasource:
    url: "jdbc:mysql://localhost:3306/onlinefilms?useUnicode=true&serverTimezone=America/Edmonton"
    username: root
    password: vip2568Gleb
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: true